name: Keep Render API Alive

on:
  schedule:
    - cron: "*/10 * * * *"  # Every 10 minutes (UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  ping-api:
    runs-on: ubuntu-latest

    steps:
      - name: Send POST to Render API
        run: |
          curl -X POST https://hira-ai.onrender.com/chat \
            -H "Content-Type: application/json" \
            -d '{"message": "ping"}'
